---
- name: Print var awxinvvar 
  debug:
    msg: "Hello World - {{ awxinvvar }}"

#- include_tasks: nginx-proxy-sites.yml

- import_tasks: nginx-proxy-sites.yml

# tasks file for roles/nginx-proxy

#- name: nginx | main config
#  become: true
#  template:
#    src: nginx-conf.j2
#    dest: /etc/nginx/nginx.conf
#    mode: 0644
#  notify:
#    - restart nginx

#- include: nginx-additional.yml
