---
# tasks file for roles/nginx-proxy streams setup

# If websockets are enabled for any proxies then it must also be enabled at
# the top level
- name: nginx | stream-conf.d directory
  become: true
  file:
    path: /etc/nginx/stream-conf.d
    state: directory
    mode: 0755

- name: nginx | stream proxy config
  become: true
  template:
    src: nginx-confd-streams.j2
    dest: /etc/nginx/stream-conf.d/proxy-streams.conf
    mode: 0644
  notify:
    - restart nginx
  when: nginx_proxy_streams

- name: nginx | stream proxy config
  become: true
  file:
    dest: /etc/nginx/stream-conf.d/proxy-streams.conf
    state: absent
  notify:
    - restart nginx
  when: not nginx_proxy_streams
