---
# tasks file for roles/nginx-proxy additional config

- name: nginx | additional maps
  become: true
  template:
    src: nginx-confd-proxy-maps.j2
    dest: /etc/nginx/conf.d/proxy-maps.conf
    mode: 0644
  notify:
    - restart nginx
