---
# tasks file for roles/nginx-proxy sites and ssl
- name: nginx | show nginx_proxy_sites  
  debug:
    msg: "nginx_proxy_sites = {{ nginx_proxy_sites }}"

# generate nginx conf file 
- name: nginx | proxy config
  become: true  
  template:
    src: nginx-confd-proxy.j2
    dest: >-
      /etc/nginx/conf.d/{{ site.nginx_proxy_server_name |
      default('default') }}.conf
    mode: 0644
  with_items: "{{ nginx_proxy_sites }}"
  loop_control:
    loop_var: site

#- name: nginx | proxy upstream servers
#  become: true
#  template:
#    src: nginx-confd-proxy-upstream.j2
#    dest: /etc/nginx/conf.d/proxy-upstream.conf
#    mode: 0644
#  notify:
#    - restart nginx
#
#- name: nginx | create proxy ssl certificate directory
#  become: true
#  file:
#    path: "{{ item.nginx_proxy_ssl_certificate | dirname }}"
#    state: directory
#    mode: 0755
#  when: "item.nginx_proxy_ssl_certificate | default(None)"
#  with_items:
#    - {nginx_proxy_ssl_certificate: "{{ nginx_proxy_ssl_certificate }}"}
#    - "{{ nginx_proxy_sites }}"
#
#- name: nginx | create proxy ssl certificate key directory
#  become: true
#  file:
#    path: "{{ item.nginx_proxy_ssl_certificate_key | dirname }}"
#    state: directory
#    mode: 0755
#  when: "item.nginx_proxy_ssl_certificate_key | default(None)"
#  with_items:
#    - {nginx_proxy_ssl_certificate_key:
#         "{{ nginx_proxy_ssl_certificate_key }}"}
#    - "{{ nginx_proxy_sites }}"
#
#- name: nginx | copy proxy ssl certificate
#  become: true
#  copy:
#    dest: "{{ item.nginx_proxy_ssl_certificate }}"
#    group: root
#    owner: root
#    mode: 0400
#    src: "{{ item.nginx_proxy_ssl_certificate_source_path }}"
#  when: "item.nginx_proxy_ssl_certificate_source_path | default(None)"
#  with_items:
#    - {nginx_proxy_ssl_certificate: "{{ nginx_proxy_ssl_certificate }}",
#       nginx_proxy_ssl_certificate_source_path:
#         "{{ nginx_proxy_ssl_certificate_source_path }}"}
#    - "{{ nginx_proxy_sites }}"
#  notify:
#    - restart nginx
#  no_log: true
#
#- name: nginx | copy proxy ssl certificate key
#  become: true
#  copy:
#    dest: "{{ item.nginx_proxy_ssl_certificate_key }}"
#    group: root
#    owner: root
#    mode: 0400
#    src: "{{ item.nginx_proxy_ssl_certificate_key_source_path }}"
#  when: "item.nginx_proxy_ssl_certificate_key_source_path | default(None)"
#  with_items:
#    - {nginx_proxy_ssl_certificate_key:
#         "{{ nginx_proxy_ssl_certificate_key }}",
#       nginx_proxy_ssl_certificate_key_source_path:
#         "{{ nginx_proxy_ssl_certificate_key_source_path }}"}
#    - "{{ nginx_proxy_sites }}"
#  notify:
#    - restart nginx
#  no_log: true
