---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: molecule/default/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: nginx-proxy
    image: centos/systemd
    image_version: latest
    command: /sbin/init
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
